# Generated by Django 3.1.7 on 2021-02-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(blank=True, help_text='主场球队', max_length=200)),
                ('away_team', models.CharField(blank=True, help_text='客场球队', max_length=200)),
                ('home_team_goals', models.SmallIntegerField(default=0, help_text='主场球队进球数')),
                ('away_team_goals', models.SmallIntegerField(default=0, help_text='客场球队进球数')),
                ('match_time', models.CharField(blank=True, help_text='比赛时间', max_length=100)),
                ('match_season', models.CharField(blank=True, help_text='赛季', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('H', '主场赢'), ('D', '平局'), ('A', '客场赢')], help_text='结果', max_length=1)),
            ],
        ),
    ]
