# Generated by Django 3.1.7 on 2021-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchdata',
            options={'ordering': ('-match_date',), 'verbose_name': '数据集', 'verbose_name_plural': '数据集'},
        ),
        migrations.AddField(
            model_name='matchdata',
            name='is_trained',
            field=models.BooleanField(default=False, verbose_name='是否已训练'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='away_team',
            field=models.CharField(blank=True, max_length=200, verbose_name='客场球队'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='away_team_goals',
            field=models.SmallIntegerField(default=0, verbose_name='客场球队进球数'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='home_team',
            field=models.CharField(blank=True, max_length=200, verbose_name='主场球队'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='home_team_goals',
            field=models.SmallIntegerField(default=0, verbose_name='主场球队进球数'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='match_date',
            field=models.DateField(blank=True, max_length=100, verbose_name='比赛日期'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='match_season',
            field=models.CharField(blank=True, max_length=20, verbose_name='赛季'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='result',
            field=models.CharField(blank=True, choices=[('H', '主场赢'), ('D', '平局'), ('A', '客场赢')], max_length=1, verbose_name='结果'),
        ),
    ]
